# Generated by Django 4.1.5 on 2023-02-09 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_remove_job_image_postimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='title',
            field=models.CharField(default='Python', max_length=50),
        ),
    ]
